### ISSUE TITLE
No module named 'core'

### ISSUE THREAD

**Issue by audreyreal** [ZeroEpoch1969/RubyRoseBot#14]
When I run "runbot.bat" the command prompt comes up but i get an error that says:
"Traceback <most recent call last>:
    File "bot.py", line 8, in <module>
        import pyping
    File "C:\Program Files\Python35\lib\site-packages\pyping\__init__.py", line 3,
   in <module>
        from core import *
ImportError: No module named 'core'"
I'm running python 3.5.4 and have installed all the requirements with pip.

**Comment by Pierce01** [comment]
you cant use pyping on windows. 

remove the import and the ping command if you want to run the bot

**Comment by Pierce01** [comment]
I PR'd a change for the ping command, so this will help fix your problem  (#15)

**Comment by script-head** [comment]
Fixed in the latest version
