### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by audreyreal** [ZeroEpoch1969/RubyRoseBot#16]
"Traceback (most recent call last):
  File "bot.py", line 185, in <module>
    @bot.before_invoke
  File "C:\Program Files\Python35\lib\site-packages\discord\client.py", line 264
, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute
 'before_invoke'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000000000438E390>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000000000438E6A0>"

running on windows 7

**Comment by robingall2910** [comment]
`AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute
'before_invoke'`

there's your issue. make sure you have discord.py's rewrite installed.

**Comment by audreyreal** [comment]
i have discord.py installed but i can't seem to find the rewrite

**Comment by Pierce01** [comment]
`python3 -m pip install -U git+https://github.com/Rapptz/discord.py@rewrite`
or with voice
`python3 -m pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]`
