### ISSUE TITLE
E621 and other related commands returning JSONDecodeError handler when called

### ISSUE THREAD

**Issue by lyricalpaws** [ZeroEpoch1969/RubyRoseBot#18]

**Comment by script-head** [comment]
I know about it, still don't know what exactly causes it.

**Comment by lyricalpaws** [comment]
My only idea would be relating to the e621 api, as they don't use json, but instead use txt. And I think that causes issues with the json module.

**Comment by Pierce01** [comment]
bot is getting the info from their JSON api

https://github.com/ZeroEpoch1969/RubyRoseBot/blob/master/commands/nsfw.py#L48

**Comment by lyricalpaws** [comment]
>.format(limit, tags)).text)

Yeahno It formats the text as json, because E621's api uses plaintext not json.

**Comment by robingall2910** [comment]
*cough* let me leave this here for @ZeroEpoch1969 
https://github.com/robingall2910/RobTheBoat/commit/f16a69b159d642e0d50c52de2280077200ed7b4a
for the header, because it shouldn't be that way
https://github.com/robingall2910/RobTheBoat/commit/9db503550e1757ad3fd74f03e62e1d3645d780e5

**Comment by script-head** [comment]
@robingall2910 bitch u got write perms do it for me

**Comment by script-head** [comment]
Should be fixed now.
