### ISSUE TITLE
Error when starting bot.

### ISSUE THREAD

**Issue by notbozho** [ZeroEpoch1969/RubyRoseBot#19]
`
[ERROR] Failed to load extension commands.information
ExtensionFailed: Extension 'commands.information' raised an error: error: bad escape \s at position 0
[CRITICAL] Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib`

I'm using python 3.8 and i have all the requirements installed

**Comment by script-head** [comment]
Damn I'm late as fuck and you either gave up or figured it out a year ago but if you're on linux you need to run "apt install opus-tools"
