### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by PotatoNoodles** [ZeroEpoch1969/RubyRoseBot#3]
My music commands won't work when I download this?

When I start up the .bat file it says:

[ERROR] Failed to load extension commands.music

Any way to fix this?

**Comment by script-head** [comment]
Download [https://github.com/CreeperSeth/RubyRoseBot/blob/master/commands/music.py](https://github.com/CreeperSeth/RubyRoseBot/blob/master/commands/music.py)
